### ISSUE TITLE
Missing custom theme CLI generator on the latest release

### ISSUE THREAD

**Issue by muco-rolle** [formaat-design/community#138]
I'm trying to generate a custom theme using Reshaped 13.1 it's not working I'm not sure what's wrong.

Here's the script ` "build:themes": "reshaped theming --output src/themes"`
 
And the following is the error stack:

```bash
 ❯ yarn build:themes
yarn run v1.22.19
$ reshaped theming --output src/themes
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '../dist/cli/theming'
Require stack:
- /home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js:7:40)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js'
  ]
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

mucotresor.com on  main [!?] via  v18.14.0 
❯ yarn build:themes
yarn run v1.22.19
$ reshaped theming --output src/themes
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '../dist/cli/theming'
Require stack:
- /home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js:7:40)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js'
  ]
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

mucotresor.com on  main [!?] via  v18.14.0 
❯ yarn build:themes
yarn run v1.22.19
$ reshaped theming --output src/themes
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '../dist/cli/theming'
Require stack:
- /home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js:7:40)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mucort/Programming/projects/muco/projects/mucotresor.com/node_modules/reshaped/bin/cli.js'
  ]
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by blvdmitry** [comment]
Thanks for pointing this out, added 1.13.2 which should solve the issue I think
